# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/africa_poverty_clean',
                'doc_host': 'https://Emily-RoseSteyn.github.io',
                'git_url': 'https://github.com/Emily-RoseSteyn/africa_poverty_clean',
                'lib_path': 'africa_poverty_clean'},
  'syms': {}}
